// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_ajames26.Models;

namespace Mission6_ajames26.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Mission6_ajames26.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Action/Comedy",
                            Director = "Brian Levant",
                            Edited = false,
                            Rating = "PG",
                            Title = "The Spy Next Door",
                            Year = 2010u
                        },
                        new
                        {
                            Id = 2,
                            Category = "Action",
                            Director = "Chad Stahelski",
                            Edited = false,
                            Rating = "R",
                            Title = "John Wick",
                            Year = 2014u
                        },
                        new
                        {
                            Id = 3,
                            Category = "Action/Adventure",
                            Director = "Steven Spielberg",
                            Edited = false,
                            Rating = "PG",
                            Title = "Raiders of the Lost Ark",
                            Year = 1981u
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
